# action.yml
name: Generate Changelog
description: Generates a changelog from commit messages between releases

inputs:
  previous_version:
    description: 'Previous version before bump'
    required: false
  current_version:
    description: 'Current version after bump'
    required: false

outputs:
  changelog:
    description: 'Generated changelog content'

runs:
  using: 'node20'
  main: 'dist/index.js'
